version: '3.9'

services:

  api:
    build:
      context: ../osscameroon-website/api/
      dockerfile: ./Dockerfile
    image: oss-api:latest
    container_name: oss-api
    ports:
      - 8811:8811

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    env_file: ./api/.env
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "psql", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost/${POSTGRES_DB}"]
      interval: 0.5s
      timeout: 1s
      retries: 4
      start_period: 1s

  frontend:
    build: ./frontend
    container_name: oss-front
    depends_on:
      - api
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8811
      REACT_ENV: development
    ports:
      - 3000:3000


volumes:
  pgadmin-data:
