version: '3.9'

services:

  api:
    build:
      context: ../osscameroon-website/api/
      dockerfile: ./Dockerfile
    image: oss-api:latest
    container_name: oss-api-container
    ports:
      - 8811:8811

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      OSS_WEBSITE_APP_USER: ${OSS_WEBSITE_APP_USER}
      OSS_WEBSITE_APP_PASSWORD: ${OSS_WEBSITE_APP_PASSWORD}
      OSS_WEBSITE_APP_DATABASE: ${OSS_WEBSITE_APP_DATABASE}
      POSTGRES_PASSWORD: "admin" # postgres admin password
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "psql", "postgresql://${OSS_WEBSITE_APP_USER}:${OSS_WEBSITE_APP_PASSWORD}@localhost/${OSS_WEBSITE_APP_DATABASE}"]
      interval: 0.5s
      timeout: 1s
      retries: 4
      start_period: 1s

  frontend:
    build: ./frontend
    container_name: oss-front
    depends_on:
      - api
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8811
      REACT_ENV: development
    ports:
      - 3000:3000


volumes:
  pgadmin-data:
