name: api check + unit test

on:
  push:
    paths:
      - .github/workflows/api-unit-test.yaml
      - api/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/api-unit-test.yaml
      - api/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          pip install virtualenv
          make install-deps

      - name: Lint with ruff
        run: make lint

      - name: Unit test
        run: make test
